// SPDX-License-Identifier: MIT OR Apache-2.0

package org.polygamma.android.origin.crypt;

/**
 * 32-bit prime constants.
 */
interface Prime32 {

	// These primes are selected to allow computing modulo in constant time.
	int P0 = 0x3f5a0001;
	int P1 = 0x3f5d0001;
	int P2 = 0x3f760001;

	/*
	 * These variables are generated by the `generateConstants` Gradle task. IF the primes above
	 * are modified, MAKE SURE to re-run `generateConstants`. We *must* generate these constants
	 * to improve dead code elimination; otherwise, we end up including more than we need to in
	 * the final AAR.
	 */

	// Bits required to represent `P{0,1,2}.
	int P0_BITS = 30;
	int P1_BITS = 30;
	int P2_BITS = 30;

	// 64-bit reciprocals of `P{0,1,2}`.
	long P0_RECIPROCAL64 = 0x40a7b2f73L;
	long P1_RECIPROCAL64 = 0x40a4a34efL;
	long P2_RECIPROCAL64 = 0x408b2c161L;

	// 128-bit reciprocals of `P{0,1,2}`.
	long P0_RECIPROCAL128_HIGH = 0x40a7b2f72L;
	long P0_RECIPROCAL128_LOW = 0xe81d4e373ed5c192L;
	long P1_RECIPROCAL128_HIGH = 0x40a4a34eeL;
	long P1_RECIPROCAL128_LOW = 0xa6a79f2ed09cd2aeL;
	long P2_RECIPROCAL128_HIGH = 0x408b2c160L;
	long P2_RECIPROCAL128_LOW = 0xd6026fbd98c7af9dL;

	// Barrett factor (mu) of `P{0,1,2}`.
	int P0_BARRETT_FACTOR = 0x814f65ee;
	int P1_BARRETT_FACTOR = 0x8149469d;
	int P2_BARRETT_FACTOR = 0x8116582c;

	// Number of limbs required to represent `P{0,1,2}`.
	int P0_LIMB_COUNT = 0x1e;
	int P1_LIMB_COUNT = 0x1e;
	int P2_LIMB_COUNT = 0x1e;

	// Whether fast reduction algorithms can be used for `P{0,1,2}`.
	boolean P0_CAN_USE_FAST_REDUCTION = true;
	boolean P1_CAN_USE_FAST_REDUCTION = true;
	boolean P2_CAN_USE_FAST_REDUCTION = true;

	// Inverses for Chinese Remainder Theorem (CRT) reconstruction.
	int P0_INVERSE_MOD_P1 = 0x151f;
	int P01_INVERSE_MOD_P2 = 0x2e708ab7;
}
