# SPDX-License-Identifier: MIT OR Apache-2.0

org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.nonTransitiveRClass=true
android.useAndroidX=true

# Region SDK is being built for. See `./origin-core/build.gradle` for possible values.
origin.region=global

# RPC host to use when device is not in a non-China territory.
origin.rpc.host=oghdr%s.pgoriginad.com

# RPC host to use when device is not in a China territory.
origin.rpc.host.cn=oghdr%s.poly-gamma.cn

# Maven group under which vendor's assets are distributed.
origin.vendor.group=org.poly-gamma.android.origin

# Name of vendor distributing SDK.
origin.vendor.name=Poly-Gamma

# Code namespace of vendor.
origin.vendor.namespace=org.polygamma.android.origin

# SDK version.
origin.version.major=1
origin.version.minor=2
origin.version.patch-level=0
origin.version.development=true

# Java Version.
org.gradle.java.home=/Users/lee/Library/Java/JavaVirtualMachines/jbr-21.0.9/Contents/Home

